// export * from './generalInfoForms/GeneralInfoForms';
// export * from './headSignInAndSignUp/HeadSignInAndSignUp';
// export * from './header/Header';
// export * from './modals';
// export * from './postInteractionBar/PostInteractionBar';
// export * from './sideBar/SideBar';
// export * from './userCard/UserCard';
// export * from '@/widget/generalInformation/accountManagement/AccountManagement';
// export * from '@/widget/generalInformation/devices/Devices';
// export * from '@/widget/generalInformation/generalInfoForms/GeneralInfoForms';
// export * from '@/widget/generalInformation/myPayments/MyPayments';
// export * from '@/widget/headSignInAndSignUp/HeadSignInAndSignUp';
// export * from '@/widget/header/Header';
// export * from '@/widget/modals';
//
// export * from '@/widget/postInteractionBar/PostInteractionBar';
// export * from '@/widget/sideBar/SideBar';
// export * from '@/widget/userCard/UserCard';

export * from './headSignInAndSignUp/HeadSignInAndSignUp';
export * from './header/Header';
export * from './modals';
export * from './myProfile/MyProfile';
export * from './postInteractionBar/PostInteractionBar';
export * from './sideBar/SideBar';
export * from './userCard/UserCard';
export { AccountManagement } from '@/widget/generalInformation/accountManagement/AccountManagement';
export { Devices } from '@/widget/generalInformation/devices/Devices';
export { GeneralInfoForms } from '@/widget/generalInformation/generalInfoForms/GeneralInfoForms';
export { MyPayments } from '@/widget/generalInformation/myPayments/MyPayments';
