import type { Metadata } from 'next';

import React from 'react';

import { AlertProvider } from '@/components/ui/alert/model/AlertProvider';
import { SideBar } from '@/components/ui/sideBar/SideBar';
import Header from '@/header/Header';
import { Roboto } from 'next/font/google';

import '../styles/index.scss';

import s from './layout.module.scss';

const inter = Roboto({ subsets: ['latin'], weight: ['300', '400', '500', '700', '900'] });

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang={'en'}>
      <body className={inter.className}>
        <AlertProvider>
          <div className={s.layout}>
            <div className={s.header}>
              <Header isAuthorized />
            </div>
            <div className={s.sidebar}>
              <SideBar />
            </div>
            <div className={s.content}>{children}</div>
          </div>
        </AlertProvider>
      </body>
    </html>
  );
}
