#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

if ! pnpm run check-format; then
    echo '❌ Prettier Check Failed. Run pnpm run format,  Problem pnpm run check-format , add changes and try commit again. ❌'
    exit 1
fi

if ! pnpm run format; then
    echo '❌ Prettier Format Failed. Problem pnpm run format , add changes and try commit again. ❌'
    exit 1
fi

if ! pnpm run check-lint; then
    echo '❌ ESLint Check Failed. Problem pnpm run check-lint, add changes and try to commit again. ❌'
    exit 1
fi

if ! pnpm run check-types; then
    echo '❌ Are you seriously trying to write that? Problem pnpm run check-types . Make the changes required above. ❌'
    exit 1
fi

echo '🤔🤔🤔🤔... Alright.... Code looks good to me... Trying to build now. 🤔🤔🤔🤔'

echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'